[package]
name = "caniuse-rs"
version = "0.1.0"
authors = ["Jonas Platte <jplatte@posteo.de>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.27"
gloo = "0.2.1"
once_cell = "1.3.1"
serde = { version = "1.0.104", features = ["derive"] }
wasm-bindgen = "0.2.59"
yew = { version = "0.14.1", features = ["web_sys"] }
yew-router = { version = "0.11.0", features = ["web_sys"] }

[dependencies.web-sys]
version = "0.3.36"
features = [
    "console",
    "Document",
    "DomStringMap",
    "Element",
    "Location",
    "HtmlElement",
    "Storage",
    "Window",
]

[build-dependencies]
proc-macro2 = "1.0.9"
serde = { version = "1.0.104", features = ["derive"] }
tera = { version = "1.1.0", default-features = false }
toml = "0.5.6"
quote = "1.0.3"

[profile.release]
opt-level = "s"
lto = true
